devices:
    - device_backend: qmi
      id: rm520n-1
      modem_imei: ""
      name: RM520N-GL QMI Cellular
email:
    enabled: false
    from_address: ""
    password: ""
    smtp_host: smtp.qq.com
    smtp_port: 587
    to_addresses: []
    username: ""
server:
    debug: false
    port: 7575
telegram:
    admin_id: 0
    base_url: ""
    bot_token: ""
    chat_id: 0
    enabled: false
    proxy: ""
web:
    password: $2b$10$v50pqRUsRc3zHBY9hILGQ.RBOEy.gU2NGFLZWvL9MgQLy6TJGax6K
    username: admin
webhook:
    enabled: false
    headers: {}
    retry_max: 3
    secret: ""
    text_template: '{{device_label}} {{text}}'
    timeout_ms: 5000
    urls: []
